export const ENABLE_NEXT_BUTTON = "ENABLE_NEXT_BUTTON";

export const REQUEST_DATA_PENDING = "REQUEST_DATA_PENDING";
export const REQUEST_DATA_SUCCESS = "REQUEST_DATA_SUCCESS";
export const REQUEST_DATA_FAILED = "REQUEST_DATA_FAILED";
export const REQUEST_JSON_DATA = " REQUEST_JSON_DATA";

export const SELECTED_JOURNEY = "SELECTED_JOURNEY";
export const SELECTED_OPTION = "SELECTED_OPTION";

export const CLICKED_NEXT = "CLICKED_NEXT";
export const CLICKED_PREV = "CLICKED_PREV";
export const CLICKED_PREV_TO_JOURNEY = "CLICKED_PREV_TO_JOURNEY";
export const CLICKED_START_OVER = "CLICKED_START_OVER";
